spring:
  profiles:
    active: blue
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 172.31.15.196

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 172.31.15.196

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  redis:
    host: localhost
    port: 6379

springdoc:
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


